import { createSlice, nanoid, type PayloadAction } from "@reduxjs/toolkit";

interface Course {
  id: string;
  title: string;
}

interface CourseState {
  courses: Course[];
}

const initialState: CourseState = {
  courses: [
    {
      id: "1",
      title: "Redux Toolkit",
    },
  ],
};

export const courseSlice = createSlice({
  name: "course",
  initialState,
  reducers: {
    addCourse: (state, action: PayloadAction<string>) => {
      //action.payload is here just simple data
      const newCourse = {
        id: nanoid(),
        title: action.payload,
      };
      state.courses.push(newCourse);
    },
    removeCourse: (state, action: PayloadAction<string>) => {
      //action.payload=courseId
      state.courses = state.courses.filter(
        (course) => course.id !== action.payload,
      );
    },
  },
});

// Action creators generated by Redux Toolkit (used by components with dispatch)
export const { addCourse, removeCourse } = courseSlice.actions;

// Reducer function generated by the slice (registered in the Redux store)
export default courseSlice.reducer;
